# VII - Algorytmy heurystyczne

Algorytm genetyczny // przepisany z Metod Heurystycznych z Mathematici

In [1]:
import numpy

class Genetic:
    def optimization(self, generations, equation_inputs, num_weights, sol_per_pop, num_parents_mating):
        pop_size = (sol_per_pop,num_weights)
        new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
        print(new_population)

        for generation in range(generations):
            print("Generation : ", generation)
            # Ocena jakości
            fitness = self.__cal_pop_fitness(equation_inputs, new_population)

            # Wybór najlepszych rodziców
            parents = self.__select_mating_pool(new_population, fitness, num_parents_mating)

            # Krzyzowanie
            offspring_crossover = self.__crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], num_weights))

            # Mutacja
            offspring_mutation = self.__mutation(offspring_crossover)

            # Selekcja
            new_population[0:parents.shape[0], :] = parents
            new_population[parents.shape[0]:, :] = offspring_mutation

            print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

        fitness = self.__cal_pop_fitness(equation_inputs, new_population)
        best_match_idx = numpy.where(fitness == numpy.max(fitness))

        print("Best solution : ", new_population[best_match_idx, :])
        print("Best solution fitness : ", fitness[best_match_idx])

    def __cal_pop_fitness(self, equation_inputs, pop):
        fitness = numpy.sum(pop*equation_inputs, axis=1)
        return fitness

    def __select_mating_pool(self, pop, fitness, num_parents):
        parents = numpy.empty((num_parents, pop.shape[1]))
        for parent_num in range(num_parents):
            max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
            max_fitness_idx = max_fitness_idx[0][0]
            parents[parent_num, :] = pop[max_fitness_idx, :]
            fitness[max_fitness_idx] = -99999999999
        return parents

    def __crossover(self, parents, offspring_size):
        offspring = numpy.empty(offspring_size)
        crossover_point = numpy.uint8(offspring_size[1]/2)

        for k in range(offspring_size[0]):
            parent1_idx = k%parents.shape[0]
            parent2_idx = (k+1)%parents.shape[0]
            offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
            offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
        return offspring

    def __mutation(self, offspring_crossover, num_mutations=1):
        mutations_counter = numpy.uint8(offspring_crossover.shape[1] / num_mutations)
        for idx in range(offspring_crossover.shape[0]):
            gene_idx = mutations_counter - 1
            for mutation_num in range(num_mutations):
                random_value = numpy.random.uniform(-1.0, 1.0, 1)
                offspring_crossover[idx, gene_idx] = offspring_crossover[idx, gene_idx] + random_value
                gene_idx = gene_idx + mutations_counter
        return offspring_crossover


inputs = [2,-1,3,5,-2.5,2.4]
weights = 6
sol_per_pop = 8
parents_mating = 4

genetic = Genetic()
genetic.optimization(5, inputs, weights, sol_per_pop, parents_mating)

[[ 2.51296663 -2.35897905 -1.08341019  2.88872121  3.77151196  0.52267973]
 [ 1.72548506 -2.147338    2.12506132  0.9413221   3.93441903  1.22235778]
 [-1.77595856  2.54901789 -1.63821959 -3.50462803  2.50190019 -1.88989499]
 [-0.14420629 -2.36324143  3.22566151 -3.41006009 -0.6880915  -3.42058589]
 [ 3.3079872   0.28548034 -0.35566631 -2.82761623  0.30357639  1.68401035]
 [ 3.99733925  1.12712226  3.80692575  1.2375529  -0.69313892 -0.60113633]
 [-3.82758392 -1.18432513 -1.60511475 -3.8744885   0.45159954 -0.54808317]
 [-0.69626903  3.4394972  -1.24287323  2.65221483  3.80352726  1.60407211]]
Generation :  0
Best result :  26.1821930244086
Generation :  1
Best result :  26.810674960697607
Generation :  2
Best result :  26.810674960697607
Generation :  3
Best result :  27.25504581611416
Generation :  4
Best result :  27.504881418845553
Best solution :  [[[ 3.99733925  1.12712226  3.80692575  1.2375529  -0.69313892
    0.5399734 ]]]
Best solution fitness :  [27.50488142]
